// AUTOASM · plantilla de la estructura académica del centro (curso 2025-26).
//
// Aquí vive SOLO la estructura: qué cursos y qué clases existen en Apple School Manager,
// con qué identificadores y a qué grupos de alumnado corresponde cada clase. **No hay
// ni un dato personal**: ni alumnos, ni profesores, ni correos. El alumnado sale de la
// BBDD central (`edu_students`) y el profesorado de `edu_teachers`; los instructores de
// cada clase se arrastran del export del curso anterior o se eligen en pantalla.
//
// Los identificadores (`Course-ESO-ESO1A`, `Cls-MatESO1A`) son los que YA están en ASM:
// si cambian, ASM no actualiza la clase, crea otra. Por eso esto es una plantilla
// editable en pantalla y no un generador de ids nuevos cada año.
//
// `grupos` es la regla de matrícula de la clase: los `grade_level` cuyo alumnado va
// dentro. Sale de cómo están hoy las matrículas reales — por ejemplo, las asignaturas de
// ESO 3A llevan también al alumnado de ESO 3 PDC, y de ahí que Religión de 3A tenga 31
// matriculados y la tutoría 19.

export interface CursoPlantilla {
  course_id: string;
  course_number: string;
  course_name: string;
}

export interface ClasePlantilla {
  class_id: string;
  /** Lo que se ve en el iPad: 'Tutoría', 'Matemáticas'… */
  class_number: string;
  course_id: string;
  /** `grade_level` del alumnado que se matricula en esta clase. Vacío = clase solo de profes. */
  grupos: string[];
}

/** El centro tal y como está dado de alta en ASM. */
export const CENTRO_PLANTILLA = {
  location_id: 'Consolacion_Burriana',
  location_name: 'Consolación Burriana (Zulu)',
};

export const CURSOS_PLANTILLA: CursoPlantilla[] = [
  { course_id: "Course-EI-EI1A", course_number: "EI1A", course_name: "Infantil 1A" },
  { course_id: "Course-EI-EI1B", course_number: "EI1B", course_name: "Infantil 1B" },
  { course_id: "Course-EI-EI2A", course_number: "EI2A", course_name: "Infantil 2A" },
  { course_id: "Course-EI-EI2B", course_number: "EI2B", course_name: "Infantil 2B" },
  { course_id: "Course-EI-EI3A", course_number: "EI3A", course_name: "Infantil 3A" },
  { course_id: "Course-EI-EI3B", course_number: "EI3B", course_name: "Infantil 3B" },
  { course_id: "Course-EP-EP1A", course_number: "EP1A", course_name: "Primaria 1A" },
  { course_id: "Course-EP-EP1B", course_number: "EP1B", course_name: "Primaria 1B" },
  { course_id: "Course-EP-EP2A", course_number: "EP2A", course_name: "Primaria 2A" },
  { course_id: "Course-EP-EP2B", course_number: "EP2B", course_name: "Primaria 2B" },
  { course_id: "Course-EP-EP3A", course_number: "EP3A", course_name: "Primaria 3A" },
  { course_id: "Course-EP-EP3B", course_number: "EP3B", course_name: "Primaria 3B" },
  { course_id: "Course-EP-EP4A", course_number: "EP4A", course_name: "Primaria 4A" },
  { course_id: "Course-EP-EP4B", course_number: "EP4B", course_name: "Primaria 4B" },
  { course_id: "Course-EP-EP5A", course_number: "EP5A", course_name: "Primaria 5A" },
  { course_id: "Course-EP-EP5B", course_number: "EP5B", course_name: "Primaria 5B" },
  { course_id: "Course-EP-EP6A", course_number: "EP6A", course_name: "Primaria 6A" },
  { course_id: "Course-EP-EP6B", course_number: "EP6B", course_name: "Primaria 6B" },
  { course_id: "Course-ESO-ESO1A", course_number: "ESO1A", course_name: "ESO 1A" },
  { course_id: "Course-ESO-ESO1B", course_number: "ESO1B", course_name: "ESO 1B" },
  { course_id: "Course-ESO-ESO1C", course_number: "ESO1C", course_name: "ESO 1C" },
  { course_id: "Course-ESO-ESO2A", course_number: "ESO2A", course_name: "ESO 2A" },
  { course_id: "Course-ESO-ESO2B", course_number: "ESO2B", course_name: "ESO 2B" },
  { course_id: "Course-ESO-ESO2C", course_number: "ESO2C", course_name: "ESO 2C" },
  { course_id: "Course-ESO-ESO3A", course_number: "ESO3A", course_name: "ESO 3A" },
  { course_id: "Course-ESO-ESO3B", course_number: "ESO3B", course_name: "ESO 3B" },
  { course_id: "Course-ESO-ESO4A", course_number: "ESO4A", course_name: "ESO 4A" },
  { course_id: "Course-ESO-ESO4B", course_number: "ESO4B", course_name: "ESO 4B" },
  { course_id: "Course-EP-EP5", course_number: "EP5", course_name: "Primaria 5" },
  { course_id: "Course-EP-EP6", course_number: "EP6", course_name: "Primaria 6" },
  { course_id: "Course-ESO-ESO1", course_number: "ESO1", course_name: "ESO1" },
  { course_id: "Course-ESO-ESO2", course_number: "ESO2", course_name: "ESO2" },
  { course_id: "Course-ESO-ESO3", course_number: "ESO3", course_name: "ESO3" },
  { course_id: "Course-ESO-ESO4", course_number: "ESO4", course_name: "ESO4" },
  { course_id: "Course-EP-EP5C", course_number: "EP5C", course_name: "Primaria 5C" },
  { course_id: "Course-EP-EP6D", course_number: "EP6D", course_name: "Primaria 6D" },
  { course_id: "Course-EI-EIComp", course_number: "InfComp", course_name: "Infantil Compartidos" },
  { course_id: "Course-EP-EPComp", course_number: "PrimComp", course_name: "Primaria Compartidos" },
  { course_id: "Course-ESO-ESO3PDC", course_number: "ESO3PDC", course_name: "ESO 3 PDC" },
  { course_id: "Course-ESO-ESO4PDC", course_number: "ESO4PDC", course_name: "ESO 4 PDC" },
  { course_id: "Course-Comp", course_number: "Comp", course_name: "Compartidos" },
];

export const CLASES_PLANTILLA: ClasePlantilla[] = [
  { class_id: "Cls-EI1A", class_number: "Tutoría", course_id: "Course-EI-EI1A", grupos: [] },
  { class_id: "Cls-EI1B", class_number: "Tutoría", course_id: "Course-EI-EI1B", grupos: [] },
  { class_id: "Cls-EI2A", class_number: "Tutoría", course_id: "Course-EI-EI2A", grupos: [] },
  { class_id: "Cls-EI2B", class_number: "Tutoría", course_id: "Course-EI-EI2B", grupos: [] },
  { class_id: "Cls-EI3A", class_number: "Tutoría", course_id: "Course-EI-EI3A", grupos: [] },
  { class_id: "Cls-EI3B", class_number: "Tutoría", course_id: "Course-EI-EI3B", grupos: [] },
  { class_id: "Cls-EIComp", class_number: "Infantil Compartidos", course_id: "Course-EI-EIComp", grupos: ["Infantil Compartido"] },
  { class_id: "Cls-EP1A", class_number: "Tutoría", course_id: "Course-EP-EP1A", grupos: [] },
  { class_id: "Cls-EP1B", class_number: "Tutoría", course_id: "Course-EP-EP1B", grupos: [] },
  { class_id: "Cls-EP2A", class_number: "Tutoría", course_id: "Course-EP-EP2A", grupos: [] },
  { class_id: "Cls-EP2B", class_number: "Tutoría", course_id: "Course-EP-EP2B", grupos: [] },
  { class_id: "Cls-EP3A", class_number: "Tutoría", course_id: "Course-EP-EP3A", grupos: [] },
  { class_id: "Cls-EP3B", class_number: "Tutoría", course_id: "Course-EP-EP3B", grupos: [] },
  { class_id: "Cls-EP4A", class_number: "Tutoría", course_id: "Course-EP-EP4A", grupos: [] },
  { class_id: "Cls-EP4B", class_number: "Tutoría", course_id: "Course-EP-EP4B", grupos: [] },
  { class_id: "Cls-EPComp", class_number: "Primaria Compartidos", course_id: "Course-EP-EPComp", grupos: ["Primaria Compartido"] },
  { class_id: "Cls-EP5A", class_number: "Tutoría", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-EP5B", class_number: "Tutoría", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-MatEP5A", class_number: "Matemáticas", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-CMEP5A", class_number: "C. del Medi", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-RelEP5A", class_number: "Religión", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-PlasEP5A", class_number: "Plástica", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-ValEP5A", class_number: "Valencià", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-MusEP5A", class_number: "Música", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-EdfEP5A", class_number: "Educación física", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-LenEP5A", class_number: "Lengua", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-IngEP5A", class_number: "Inglés", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-EdVEP5A", class_number: "Ed. Valores", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-ProEP5A", class_number: "Proyectos", course_id: "Course-EP-EP5A", grupos: ["PRIMARIA 5A"] },
  { class_id: "Cls-MatEP5B", class_number: "Matemáticas", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-CMEP5B", class_number: "C. del Medi", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-RelEP5B", class_number: "Religión", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-PlasEP5B", class_number: "Plástica", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-ValEP5B", class_number: "Valencià", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-MusEP5B", class_number: "Música", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-EdfEP5B", class_number: "Educación física", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-LenEP5B", class_number: "Lengua", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-IngEP5B", class_number: "Inglés", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-EdVEP5B", class_number: "Ed. Valores", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-ProEP5B", class_number: "Proyectos", course_id: "Course-EP-EP5B", grupos: ["PRIMARIA 5B"] },
  { class_id: "Cls-EP6A", class_number: "Tutoría", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-EP6B", class_number: "Tutoría", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-MatEP6A", class_number: "Matemáticas", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-CMEP6A", class_number: "C. del Medi", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-RelEP6A", class_number: "Religión", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-PlasEP6A", class_number: "Plástica", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-ValEP6A", class_number: "Valencià", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-MusEP6A", class_number: "Música", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-EdfEP6A", class_number: "Educación física", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-LenEP6A", class_number: "Lengua", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-IngEP6A", class_number: "Inglés", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-ProEP6A", class_number: "Proyectos", course_id: "Course-EP-EP6A", grupos: ["PRIMARIA 6A"] },
  { class_id: "Cls-MatEP6B", class_number: "Matemáticas", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-CMEP6B", class_number: "C. del Medi", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-RelEP6B", class_number: "Religión", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-PlasEP6B", class_number: "Plástica", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-ValEP6B", class_number: "Valencià", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-MusEP6B", class_number: "Música", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-EdfEP6B", class_number: "Educación física", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-LenEP6B", class_number: "Lengua", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-IngEP6B", class_number: "Inglés", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-ProEP6B", class_number: "Proyectos", course_id: "Course-EP-EP6B", grupos: ["PRIMARIA 6B"] },
  { class_id: "Cls-ESO1A", class_number: "Tutoría", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-ByGESO1A", class_number: "Biología y Geología", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-GyHESO1A", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-LenESO1A", class_number: "Lengua", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-MatESO1A", class_number: "Matemáticas", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-IngESO1A", class_number: "Inglés", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-EFESO1A", class_number: "Educación física", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-MusESO1A", class_number: "Música", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-TecESO1A", class_number: "Tecnología y Digitalización", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-RelESO1A", class_number: "Religión", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-ValESO1A", class_number: "Valencià", course_id: "Course-ESO-ESO1A", grupos: ["ESO 1A"] },
  { class_id: "Cls-FranESO1", class_number: "Francés", course_id: "Course-ESO-ESO1", grupos: ["ESO 1A", "ESO 1B"] },
  { class_id: "Cls-TRDigSESO1", class_number: "Taller Recursos Digitales Saludables", course_id: "Course-ESO-ESO1", grupos: ["ESO 1A", "ESO 1B"] },
  { class_id: "Cls-TValESO1", class_number: "", course_id: "Course-ESO-ESO1", grupos: ["ESO 1A", "ESO 1B"] },
  { class_id: "Cls-TMatESO1", class_number: "Taller Matemáticas", course_id: "Course-ESO-ESO1", grupos: ["ESO 1A", "ESO 1B"] },
  { class_id: "Cls-ESO1B", class_number: "Tutoría", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-ByGESO1B", class_number: "Biología y Geología", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-GyHESO1B", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-LenESO1B", class_number: "Lengua", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-MatESO1B", class_number: "Matemáticas", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-IngESO1B", class_number: "Inglés", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-EFESO1B", class_number: "Educación física", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-MusESO1B", class_number: "Música", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-TecESO1B", class_number: "Tecnología", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-RelESO1B", class_number: "Religión", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-ValESO1B", class_number: "Valencià", course_id: "Course-ESO-ESO1B", grupos: ["ESO 1B"] },
  { class_id: "Cls-ESO2A", class_number: "Tutoría", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-FyQESO2A", class_number: "Física y Química", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-GyHESO2A", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-LenESO2A", class_number: "Lengua", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-MatESO2A", class_number: "Matemáticas", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-IngESO2A", class_number: "Inglés", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-EFESO2A", class_number: "Educación física", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-MusESO2A", class_number: "Música", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-RelESO2A", class_number: "Religión", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-ValESO2A", class_number: "Valencià", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-PlasESO2A", class_number: "Plástica", course_id: "Course-ESO-ESO2A", grupos: ["ESO 2A"] },
  { class_id: "Cls-FranESO2", class_number: "Francés", course_id: "Course-ESO-ESO2", grupos: ["ESO 2A", "ESO 2B"] },
  { class_id: "Cls-TValESO2", class_number: "Taller Valencià", course_id: "Course-ESO-ESO2", grupos: ["ESO 2A", "ESO 2B"] },
  { class_id: "Cls-PIARESO2", class_number: "Programación, inteligencia artificial y robótica", course_id: "Course-ESO-ESO2", grupos: ["ESO 2A", "ESO 2B"] },
  { class_id: "Cls-ESO2B", class_number: "Tutoría", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-FyQESO2B", class_number: "Física y Química", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-GyHESO2B", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-LenESO2B", class_number: "Lengua", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-MatESO2B", class_number: "Matemáticas", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-IngESO2B", class_number: "Inglés", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-EFESO2B", class_number: "Educación física", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-MusESO2B", class_number: "Música", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-RelESO2B", class_number: "Religión", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-ValESO2B", class_number: "Valencià", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-PlasESO2B", class_number: "Plástica", course_id: "Course-ESO-ESO2B", grupos: ["ESO 2B"] },
  { class_id: "Cls-ESO3A", class_number: "Tutoría", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-ByGESO3A", class_number: "Biología y Geología", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-FyQESO3A", class_number: "Física y Química", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-GyHESO3A", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-LenESO3A", class_number: "Lengua", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-MatESO3A", class_number: "Matemáticas", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-IngESO3A", class_number: "Inglés", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-EFESO3A", class_number: "Educación física", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3 PDC", "ESO 3A"] },
  { class_id: "Cls-TecESO3A", class_number: "Tecnología y Digitalización", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-RelESO3A", class_number: "Religión", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3 PDC", "ESO 3A"] },
  { class_id: "Cls-ValESO3A", class_number: "Valencià", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-PlasESO3A", class_number: "Plástica", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A"] },
  { class_id: "Cls-MusESO3A", class_number: "Música", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3 PDC", "ESO 3A"] },
  { class_id: "Cls-ESO3B", class_number: "Tutoría", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-ByGESO3B", class_number: "Biología y Geología", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-FyQESO3B", class_number: "Física y Química", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-GyHESO3B", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-LenESO3B", class_number: "Lengua", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-MatESO3B", class_number: "Matemáticas", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-IngESO3B", class_number: "Inglés", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-EFESO3B", class_number: "Educación física", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-TecESO3B", class_number: "Tecnología", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-RelESO3B", class_number: "Religión", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-ValESO3B", class_number: "Valencià", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-PlasESO3B", class_number: "Plástica", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-MusESO3B", class_number: "Música", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3B"] },
  { class_id: "Cls-FranESO3", class_number: "Francés", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3A", "ESO 3B"] },
  { class_id: "Cls-TCOESO3", class_number: "Comunicación Oral", course_id: "Course-ESO-ESO3A", grupos: ["ESO 3 PDC", "ESO 3A", "ESO 3B"] },
  { class_id: "Cls-PIARESO3", class_number: "Programación, inteligencia artificial y robótica", course_id: "Course-ESO-ESO3B", grupos: ["ESO 3 PDC", "ESO 3A", "ESO 3B"] },
  { class_id: "Cls-ProESO3", class_number: "Proyecto", course_id: "Course-ESO-ESO3", grupos: ["ESO 2A", "ESO 3 PDC", "ESO 3A"] },
  { class_id: "Cls-ESO4A", class_number: "Tutoría", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-GyHESO4A", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-LenESO4A", class_number: "Lengua", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-MatAESO4A", class_number: "Matemáticas A", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-MatBESO4A", class_number: "Matemáticas B", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-IngESO4A", class_number: "Inglés", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-EFESO4A", class_number: "Educación física", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4 PDC", "ESO 4A"] },
  { class_id: "Cls-RelESO4A", class_number: "Religión", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4 PDC", "ESO 4A"] },
  { class_id: "Cls-ValESO4A", class_number: "Valencià", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-EArtESO4A", class_number: "Expresión Artísitica", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-EconESO4A", class_number: "Economía y emprendimiento", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-EdValESO4A", class_number: "Educ. En Valores", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4 PDC", "ESO 4A"] },
  { class_id: "Cls-LatESO4A", class_number: "Latin", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-DigESO4A", class_number: "Digitalización", course_id: "Course-ESO-ESO4A", grupos: ["ESO 4A"] },
  { class_id: "Cls-ProESO4", class_number: "Proyecto", course_id: "Course-ESO-ESO4", grupos: ["ESO 4 PDC", "ESO 4A", "ESO 4B"] },
  { class_id: "Cls-COESO4", class_number: "Competencia Comunicación Oral", course_id: "Course-ESO-ESO4", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-FranESO4", class_number: "Francés", course_id: "Course-ESO-ESO4", grupos: ["ESO 4B"] },
  { class_id: "Cls-TProfESO4", class_number: "Taller Profundización", course_id: "Course-ESO-ESO4", grupos: ["ESO 4B"] },
  { class_id: "Cls-ESO4B", class_number: "Tutoría", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-GyHESO4B", class_number: "Geografía e Historia", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-LenESO4B", class_number: "Lengua", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-MatBESO4B", class_number: "Matemáticas B", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-IngESO4B", class_number: "Inglés", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-EFESO4B", class_number: "Educación física", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-RelESO4B", class_number: "Religión", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-ValESO4B", class_number: "Valencià", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-ByGESO4B", class_number: "Biología y Geología", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-FyQESO4B", class_number: "Física y Química", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-DigESO4B", class_number: "Digitalización", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4B"] },
  { class_id: "Cls-EdValESO4B", class_number: "Educ. En Valores", course_id: "Course-ESO-ESO4B", grupos: ["ESO 4A", "ESO 4B"] },
  { class_id: "Cls-EP5C", class_number: "Tutoría", course_id: "Course-EP-EP5C", grupos: ["PRIMARIA 5C"] },
  { class_id: "Cls-TutEP6D", class_number: "Repositorio", course_id: "Course-EP-EP6D", grupos: ["PRIMARIA 5C"] },
  { class_id: "Cls-EP5", class_number: "Tutoría", course_id: "Course-EP-EP5", grupos: ["PRIMARIA 5A", "PRIMARIA 5B"] },
  { class_id: "Cls-EP6", class_number: "Tutoría", course_id: "Course-EP-EP6", grupos: ["PRIMARIA 6A", "PRIMARIA 6B"] },
  { class_id: "Cls-ESO1", class_number: "Tutoría", course_id: "Course-ESO-ESO1", grupos: ["ESO 1A", "ESO 1B"] },
  { class_id: "Cls-ESO2", class_number: "Tutoría", course_id: "Course-ESO-ESO2", grupos: ["ESO 2A", "ESO 2B"] },
  { class_id: "Cls-ESO3", class_number: "Tutoría", course_id: "Course-ESO-ESO3", grupos: ["ESO 3 PDC", "ESO 3A", "ESO 3B"] },
  { class_id: "Cls-ESO4", class_number: "Tutoría", course_id: "Course-ESO-ESO4", grupos: ["ESO 4 PDC", "ESO 4A", "ESO 4B"] },
  { class_id: "Cls-ESO3PDC", class_number: "Tutoría", course_id: "Course-ESO-ESO3PDC", grupos: ["ESO 3 PDC"] },
  { class_id: "Cls-ALESO3PDC", class_number: "Ámbito Lingüístico y social", course_id: "Course-ESO-ESO3PDC", grupos: ["ESO 3 PDC"] },
  { class_id: "Cls-ACESO3PDC", class_number: "Ámbito Científico", course_id: "Course-ESO-ESO3PDC", grupos: ["ESO 3 PDC"] },
  { class_id: "Cls-APESO3PDC", class_number: "Ámbito Práctico", course_id: "Course-ESO-ESO3PDC", grupos: ["ESO 3 PDC"] },
  { class_id: "Cls-Comp", class_number: "Compartidos", course_id: "Course-Comp", grupos: ["Infantil Compartido", "Primaria Compartido"] },
  { class_id: "Cls-ESO4PDC", class_number: "Tutoría", course_id: "Course-ESO-ESO4PDC", grupos: ["ESO 4 PDC"] },
  { class_id: "Cls-ALESO4PDC", class_number: "Ámbito Lingüístico y social", course_id: "Course-ESO-ESO4PDC", grupos: ["ESO 4 PDC"] },
  { class_id: "Cls-ACESO4PDC", class_number: "Ámbito Científico", course_id: "Course-ESO-ESO4PDC", grupos: ["ESO 4 PDC"] },
  { class_id: "Cls-APESO4PDC", class_number: "Ámbito Práctico", course_id: "Course-ESO-ESO4PDC", grupos: ["ESO 4 PDC"] },
];

/** Todos los `grade_level` que la plantilla espera encontrar, en el orden en que se pintan. */
export const GRUPOS_PLANTILLA: string[] = Array.from(
  new Set(CLASES_PLANTILLA.flatMap((c) => c.grupos)),
).sort((a, b) => a.localeCompare(b, 'es'));
